export const BLACK = 'BLACK';
export const WHITE = 'WHITE';
export const BACKGROUND_TEMPLATE_1 = 'BACKGROUND_TEMPLATE_1';
export const BACKGROUND_TEMPLATE_2 = 'BACKGROUND_TEMPLATE_2';
export const BACKGROUND_TEMPLATE_3 = 'BACKGROUND_TEMPLATE_3';
export const BACKGROUND_TEMPLATE_4 = 'BACKGROUND_TEMPLATE_4';
